### ISSUE TITLE
scrollphat.set_buffer()

### ISSUE THREAD

**Issue by adam-macgill** [pimoroni/scroll-phat#35] opened 2016-02-29 18:03 UTC
In general and in the sine.py example am getting AttributeError: 'module' object has no attribute 'set_buffer'

New to this so might be me - otherwise scrollphat is superb and all other examples working - including the excellent weather parser

Cheers

Adam

**Comment by alexellis** [comment] 2016-03-02 22:48
@adam-macgill Hi Adam, how did you install the scrollphat library? (did you use the curl/bash approach or clone the github repository?)

If you cloned, try a `git pull`

It sounds related to a change I was involved in - but this was also tested out by several people. So I am thinking you may have an old version of a file somewhere.

Alex

**Comment by alexellis** [comment] 2016-03-17 20:33
@adam-macgill how did you get on? Can we close the issue?

**Comment by adam-macgill** [comment] 2016-03-18 14:23
Hi - yes all fine thanks

**Comment by joosteto** [comment] 2016-03-27 19:48
Well, the issue is that the current
  curl -sS get.pimoroni.com/scrollphat | bash
installs an old version of the library, that doesn't have set_buffer, nor set_pixels.
So when I tried to run "sine.py" or "test-all.py" from the examples, both failed.

Please upgrade the library that the above curl/bash command installs before closing this report!

**Comment by alexellis** [comment] 2016-03-27 21:02
@joosteto OK best to call @Gadgetoid

**Comment by Gadgetoid** [comment] 2016-03-30 13:41
I have pushed up version 0.0.6 to pip which includes set_buffer. To keep you on your toes, the rotation property has been changed to the method "set_rotate".

**Closed** 2016-07-06 13:50 UTC
